name: Build, Run, and Test Docker Image

on: [push]  # Trigger on code push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t pipeline_app pipeline_app

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 pipeline_app

      - name: Test Status Page
        run: |
          sleep 5  # Allow container to start
          curl --fail http://localhost:8000/status

      - name: Test Index Page
        run: |
          sleep 5  # Allow container to start
          curl --fail http://localhost:8000/
