name: Run Makefile on Pull Requests and Main Pushes

on:
    pull_request:  # Trigger on any pull request
      paths: # Trigger only when files in these paths change
        - '.github/workflows/run_tests.yml'
        - 'pipeline_app/**'
    push:
      branches: [ main ] # Trigger on pushes to the main branch
      paths: # Trigger only when files in these paths change
        - '.github/workflows/run_tests.yml'
        - 'pipeline_app/**'

jobs:
  execute_makefile:
    runs-on: ubuntu-latest  # Specify the runner OS
    steps:
      - uses: actions/checkout@v4  # Checkout the repository
      - name: Set up Python with your Makefile's version
        uses: actions/setup-python@v5  # Example with Python, adapt as needed
        with:
          python-version: '3.13.3'  # Replace with the version your Makefile uses
      - uses: hashicorp/setup-terraform@v3
      
      - name: Install dependencies
        run: make setup-pythonenv venv tflint  # Assuming your Makefile targets

      - name: Execute pre-commit checks
        run: make precommit
        
